name: Create Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build executable
        run: |
          x86_64-w64-mingw32-g++ -static -o sukuna.exe src/*.cpp

      - name: Copy files
        run: |
          mkdir release
          cp sukuna.exe release/
          cp -r util/win/* release/

      - name: Zip files
        run: |
          cd release
          zip -r sukuna-release.zip *

      - name: Create release
        uses: actions/upload-artifact@v3
        with:
          name: sukuna-release
          path: release/sukuna-release.zip

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Sukuna Release ${{ github.run_number }}
          body: |
            Automated release created by GitHub Actions
          draft: false
          prerelease: false
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          artifact: sukuna-release