name: Build and Commit Zip

on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build executable
        run: |
          x86_64-w64-mingw32-g++ -static -o sukuna.exe src/*.cpp

      - name: Prepare release directory
        run: |
          mkdir -p release
          cp sukuna.exe release/
          cp -r util/win/* release/

      - name: Zip release files
        run: |
          cd release
          zip -r sukuna-release.zip *

      - name: Commit and push release zip
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b add-release-zip
          git add release/sukuna-release.zip
          git commit -m "Add sukuna-release.zip to release directory"
          git push origin add-release-zip
