name: Build and Upload Zip

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build executable
        run: |
          x86_64-w64-mingw32-g++ -static -o sukuna.exe src/*.cpp

      - name: Prepare release directory
        run: |
          mkdir -p release
          cp sukuna.exe release/
          cp -r util/win/* release/

      - name: Zip release files
        run: |
          cd release
          zip -r sukuna-release.zip *

      - name: Upload release directory to repository
        run: |
          mkdir -p $GITHUB_WORKSPACE/release
          cp release/sukuna-release.zip $GITHUB_WORKSPACE/release/
